name: Deploy

on: push

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create ssh directory
        run: |
          mkdir -p "$HOME/.ssh"
          
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> "$HOME/.ssh/known_hosts"
          
      - name: Update remote repo
        run: |
          ssh \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "cd /home/www/gatemap-viewer/ && git pull"
          echo "Updated remote repo"
